# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

- name: hunyuanvideo.default
  tags: [release, mad, lucid, instinct, gfx942, gfx950]
  model: tencent/HunyuanVideo
  revision: refs/pr/18
  runner: xdit
  args:
    prompt: In the large cage, two puppies were wagging their tails at each other.
    batch_size: 1
    height: 720
    width: 1280
    seed: 1168860793
    num_frames: 129
    num_inference_steps: 50
    warmup_calls: 1
    num_iterations: 1
    ulysses_degree: 8
    enable_tiling: True
    enable_slicing: True
    guidance_scale: 6.0
    use_torch_compile: True
    attention_backend: aiter

- name: hunyuanvideo.fp8attn
  tags: [release, instinct, gfx942, gfx950]
  model: tencent/HunyuanVideo
  revision: refs/pr/18
  runner: xdit
  args:
    prompt: In the large cage, two puppies were wagging their tails at each other.
    batch_size: 1
    height: 720
    width: 1280
    seed: 1168860793
    num_frames: 129
    num_inference_steps: 50
    warmup_calls: 1
    num_iterations: 1
    ulysses_degree: 8
    enable_tiling: True
    enable_slicing: True
    guidance_scale: 6.0
    use_torch_compile: True
    attention_backend: aiter_fp8

- name: hunyuanvideo.sageattn.gfx942
  tags: [release, instinct, gfx942]
  model: tencent/HunyuanVideo
  revision: refs/pr/18
  runner: xdit
  args:
    prompt: In the large cage, two puppies were wagging their tails at each other.
    batch_size: 1
    height: 720
    width: 1280
    seed: 1168860793
    num_frames: 129
    num_inference_steps: 50
    warmup_calls: 1
    num_iterations: 1
    ulysses_degree: 8
    enable_tiling: True
    enable_slicing: True
    guidance_scale: 6.0
    use_torch_compile: True
    attention_backend: aiter_i8fp8

- name: hunyuanvideo.sageattn.gfx950
  tags: [release, instinct, gfx950]
  model: tencent/HunyuanVideo
  revision: refs/pr/18
  runner: xdit
  args:
    prompt: In the large cage, two puppies were wagging their tails at each other.
    batch_size: 1
    height: 720
    width: 1280
    seed: 1168860793
    num_frames: 129
    num_inference_steps: 50
    warmup_calls: 1
    num_iterations: 1
    ulysses_degree: 8
    enable_tiling: True
    enable_slicing: True
    guidance_scale: 6.0
    use_torch_compile: True
    use_hybrid_attn_schedule: True
    hybrid_attn_low_precision_backend: aiter_i8fp8
    hybrid_attn_high_precision_backend: aiter

- name: hunyuanvideo.default.hopper
  tags: [lucid, hopper, h100, h200]
  model: tencent/HunyuanVideo
  revision: refs/pr/18
  runner: xdit
  args:
    prompt: In the large cage, two puppies were wagging their tails at each other.
    batch_size: 1
    height: 720
    width: 1280
    seed: 1168860793
    num_frames: 129
    num_inference_steps: 50
    warmup_calls: 1
    num_iterations: 1
    ulysses_degree: 8
    enable_tiling: True
    enable_slicing: True
    guidance_scale: 6.0
    use_torch_compile: True
    attention_backend: flash_3

- name: hunyuanvideo.default.blackwell
  tags: [lucid, blackwell, b200, b300]
  model: tencent/HunyuanVideo
  revision: refs/pr/18
  runner: xdit
  args:
    prompt: In the large cage, two puppies were wagging their tails at each other.
    batch_size: 1
    height: 720
    width: 1280
    seed: 1168860793
    num_frames: 129
    num_inference_steps: 50
    warmup_calls: 1
    num_iterations: 1
    ulysses_degree: 8
    enable_tiling: True
    enable_slicing: True
    guidance_scale: 6.0
    use_torch_compile: True
    attention_backend: cudnn
